library(vcfR)
library(ape)
vcf <- read.vcfR(snakemake@input[['vcf']], verbose = FALSE )
dna <- ape::read.dna(snakemake@input[['dna']], format = "fasta")
gff <- read.table(snakemake@input[['gff']], sep="\t", quote="")
chrom <- create.chromR(name='Supercontig', vcf=vcf, seq=dna, ann=gff)
pdf(file = snakemake@output[["out"]])
plot(chrom)
dev.off()
