# Base parameters

# Path data dir
data_dir: "C:/Users/joric/DataprocessingData/"

# Adapter seq for cutadapt
cutadpt: "AGATCGGAA"

# Path to the fastq file relative to data_dir
fastq_file: "FASTQ/SRR2073061.fastq.gz"

# Path to the refgen.fa file relative to data_dir
refgen: "refgen/refgen.fa"

# Path to gff file relative to data_dir
gff: "gff/Glycinemax.gff3"

# Maximum amount of threads snakemake can use
threads: 8
